name: Deploy to Packagist

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Update Packagist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run tests to ensure release stability
        run: composer test

      - name: Update Packagist
        run: |
          echo "Updating package on Packagist..."
          curl -X POST -H "Content-Type: application/json" \
          -H "Authorization: http-basic ${{ secrets.PACKAGIST_USERNAME }} ${{ secrets.PACKAGIST_TOKEN }}" \
          https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }} \
          -d '{"repository":{"url":"https://github.com/mohamedhabibwork/laravel-oci-driver"}}'

      - name: Verify Packagist update
        run: |
          echo "Waiting for Packagist to update..."
          sleep 10
          echo "You can view your package at https://packagist.org/packages/mohamedhabibwork/laravel-oci-driver"
