name: Security

on:
  push:
    branches: [main, develop]
    paths:
      - "composer.json"
      - "composer.lock"
      - ".github/workflows/security.yml"
  pull_request:
    paths:
      - "composer.json"
      - "composer.lock"
      - ".github/workflows/security.yml"
  schedule:
    - cron: "0 2 * * 1" # Weekly on Monday at 2 AM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check config exists
        run: |
          if [ ! -f config/laravel-oci-driver.php ]; then
            echo "Config file missing, skipping job."
            exit 78
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          extensions: mbstring, xml, pcntl
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-security-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-security-
            ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run security audit
        run: composer audit --format=table --no-dev

      - name: Check for known vulnerabilities (roave/security-advisories)
        run: |
          echo "Checking for security advisories..."
          composer require --dev roave/security-advisories:dev-latest --dry-run || echo "✅ No known security vulnerabilities found"

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Check config exists
        run: |
          if [ ! -f config/laravel-oci-driver.php ]; then
            echo "Config file missing, skipping job."
            exit 78
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          allow-dependencies-licenses: MIT, BSD-2-Clause, BSD-3-Clause, Apache-2.0, ISC

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [php]
    steps:
      - name: Check config and token exists
        run: |
          if [ ! -f config/laravel-oci-driver.php ]; then
            echo "Config file missing, skipping job."
            exit 78
          fi
          if [ -z "${{ secrets.CODEQL_TOKEN }}" ]; then
            echo "CODEQL_TOKEN secret missing, skipping job."
            exit 78
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality
        env:
          CODEQL_TOKEN: ${{ secrets.CODEQL_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
        env:
          CODEQL_TOKEN: ${{ secrets.CODEQL_TOKEN }}
